header = "/* GSW TEOS-10 V3.05 definitions and prototypes. */"
include_guard = "GSWTEOS_10_H"
language = "C"
no_includes = true
cpp_compat = true
#sys_includes = ["stdio", "stdlib", "string", "math", "errno"]

[fn]
sort_by = "Name"
